### ISSUE TITLE
train() is not implemented

### ISSUE THREAD

**Issue by bontorhumala** [MingjunZhong/LatentBayesianMelding#2]
Hi, I am trying this algorithm to disaggregate smart meter data on REDD dataset. I have installed mosek v7 and LatentBayesianMelding. However, when I call lbm.train() i got error:

> Traceback (most recent call last):
>   File "<stdin>", line 7, in <module>
>   File "/home/bontor/anaconda2/envs/nilmtk-env/lib/python2.7/site-packages/LatentBayesianMelding/latent_Bayesian_melding.py", line 136, in train
>     raise NotImplementedError()
> NotImplementedError

Here is the code:
`from LatentBayesianMelding import latent_Bayesian_melding as lbm`
`...`
`lbm_disagg = lbm.LatentBayesianMelding();`
`predicted_priors_elec = rtd.get_predicted_priors(ds, house_id, train_start_date, num_days, is_original=orig_test);`
`lbm_disagg.train(predicted_priors_elec);`

I find that this NotImplementedError thing is also mentioned here: https://github.com/nilmtk/nilmtk/pull/465

If it is not implemented, is there any way to train the LBM disaggregator?

**Comment by MingjunZhong** [comment]
The method `train()' is not used for training. Instead, the method `import_model()' is used to import the trained parameters, which are stored in a file *.json. I will upload an example of this file later, and also a demo showing how to use it.

**Comment by bontorhumala** [comment]
thanks for the prompt reply. is this a general parameters (i.e. work for every house from all datasets) or is the trained parameters unique for each house?

**Comment by MingjunZhong** [comment]
These parameters are general parameters; that means I use one data set to get these parameters, and then they are used for prediction for a different data set.

**Comment by bontorhumala** [comment]
I see. Thanks! I will try them as soon as the JSON file is available. Great work

**Comment by MingjunZhong** [comment]
I have updated all the code and data files, now you can try it. Let me know if there are any problems.

**Comment by bontorhumala** [comment]
Thanks. I tried (inside LatentBayesianMelding/lbm/)

`python demo_latentBayesianMelding.py`

It shows some logs (e.g 'Solving the problem...') but no plot is shown in the end. It just finished. Then I run python console, copy pasting the whole demo_latentBayesianMelding.py, got this error:

![image](https://user-images.githubusercontent.com/943854/29892608-7adbdc40-8dcf-11e7-9a6d-a501d5303143.png)

When I removed 'cooker', i got similar error (this time 'Key error: kettle');

**Comment by MingjunZhong** [comment]
Hi, It is good that I can see the prediction has done finally. Now it is only the problem of plotting the results. There are two options: 1) You can use Spyder IDE to run the demo code, then it should be able to plot the results; 2) I can improve the code to make it works when you run it in bash line.

**Comment by bontorhumala** [comment]
Yeah, I can see the disaggregation results but not the plot. Thats not a big issue. Thanks! My question is solved now
