### ISSUE TITLE
AttributeError: type object 'Variable' has no attribute 'reshape'

### ISSUE THREAD

**Issue by loneharoon** [MingjunZhong/LatentBayesianMelding#3]
System information: macOS
Python: 3.5 and also checked on 2.4
Mosek: Installed version 8.1.34 via Anaconda

I have downloaded all the files of lbm folder, and on running `demo_latentBayesainMeldyding.py` I get the following error 

```
Traceback (most recent call last):

  File "<ipython-input-54-f2cdc702cfe4>", line 1, in <module>
    results = lbm.disaggregate_chunk(mains)

  File "/Volumes/MacintoshHD2/Users/haroonr/Downloads/lbm/latent_Bayesian_melding.py", line 225, in disaggregate_chunk

  File "/Volumes/MacintoshHD2/Users/haroonr/Downloads/lbm/latent_Bayesian_melding.py", line 339, in disaggregate_fixedPrecision
    Variable.reshape(stateVariableOfAppliance[appliance].

AttributeError: type object 'Variable' has no attribute 'reshape'
```
Also, I do not find where is `Variable` declared. What does it store and what is its type?

**Comment by MingjunZhong** [comment]
The problem came from the Mosek version 8.1.34 you are using. If you use Mosek 7.1.15 with python 2.7, it will disappear. You can read the readme.md in my repository.
'Variable' is already imported after `from mosek.fusion import *'.
Hopefully this will help

**Comment by loneharoon** [comment]
Thanks. I will try.
