### ISSUE TITLE
Understanding model parameters in JSON file

### ISSUE THREAD

**Issue by loneharoon** [MingjunZhong/LatentBayesianMelding#5]
To get the model parameters for new appliances, I went through both the JSON file and the NIPS 2015 paper. Please correct me if I am wrong in explaining my points:

1.  In section 5.2 of the paper, total energy consumption of any appliance is computed using 
<img width="89" alt="screen shot 2017-12-15 at 13 42 45" src="https://user-images.githubusercontent.com/8012729/34045021-3fb40d76-e19f-11e7-8f58-e305bb0d8448.png">. Is this formula correct? For each appliance, we have more than one state (and different mean consumption for each state). Don't we need another summation sign to include mean consumption for each state separately as you have done in other two successive formulas of the paper?
2. For computing duration of appliance usage (second formula in section 5.2), is sampling rate in seconds or minutes or some other unit?
3. I have taken the following picture from your JSON file, which highlights the Kettle parameters as
![screen shot 2017-12-15 at 14 02 59](https://user-images.githubusercontent.com/8012729/34045449-d15cf1b0-e1a0-11e7-9776-0511c67d2e10.png)
Under `numberOfCyclesStats`, you have 5 features and each of them has a list of size 7.  Does these 7 readings correspond to 7 different days or something else? For other appliances, this number is different.
4. How does `numberOfSamples`, and `numberOfCyclesProb` are computed?
5. I did not find any explanation about `sac`,`appliance code map`, `induced density of sac` and `induced density of duration` in the paper. It would be great if you can give one line explanation what these parameters are and how are they computed. I think a running example in README file will be a great thing to make it easy for other people to use LBM.

**Comment by MingjunZhong** [comment]
1. The energy consumption which is denoted by τ in section 5.2 is computed simply by adding up appliance readings. This formula is the one used in the optimization problem to infer all the states `S'. This formula here is approximate to the τ.
2. I remember it was 2 minutes for that data (HES data), which means Δt=2 minutes.
3. `7' means here 7 number of cycles, I cannot remember exactly, it should be something like numberOfCycles = [1,2,3,4,5,6,7], where each element indicates how many times a kettle was used. For the washing machine, there will be less number of cycles than kettle.
4. numberOfSamples means how many examples in the data given the number of cycles. numberOfCyclesProb means the distribution of the number of cycles, if you think `number of cycles' as a discrete random variable, then numberOfCyclesProb is its distribution.
5. These variables were used in my NIPS2014 paper, but not used here. I should have explained it in my code. There is toy example in the current LBM code - I think you already have seen it?
I am not sure if I have answered all your questions, but please let me know if you have any further questions.

**Comment by loneharoon** [comment]
Thanks for the clarification. Few more questions are

1. Number of cycles for an appliance are computed day wise and this process repeats for 10 days (mentioned in NIPS 2015). Am I right?
2. I read NIPS 2014 paper but it does not explain with example how to compute `sac` parameters. Further, I  removed all `sac` parameters from your JSON for all applainces and then run `demo_latentBayesianMelding.py`. During run, several errors raised such as `keyError: induced density of sac`. So, it seems that computing `sac` parameters are required to run LBM. Any reference or example to compute such parameters will be helpful.

**Comment by MingjunZhong** [comment]
1. Yes number of cycles are computed day wise, but this process repeats more than 10 days. I cannot remember exact number of days, but I remember for some appliances for example kettle, it was a few thousand days. Can you check the `number of samples' in the JSON file, which should indicate number of days? 
2. Yes LBM should also use SAC, which is the total energy consumption - the value for SAC is shown in the JSON file.
Have I answered your questions? Any questions are welcome. If it is not clear, please let me know.
Thank you for all these useful questions; it really needs a long paper to explain these issues, including how to represent the problem as a SOCP - I really need to do this.

**Comment by loneharoon** [comment]
I am sorry for disturbing again and again. I think following questions still need clarification:

1. Regarding SAC there are three more parameters such as sac sample, induced density of sac, and  induced density of duration. Can you briefly mention what does these mean and how should I compute them?
2. Also, What does appliance code map mean?

**Comment by MingjunZhong** [comment]
1. SAC sample: the SAC examples (samples) - one sample per day. Induced density of sac: the first value is the mean of SAC examples, and the second is the std value of the SAC examples. Induced density of duration: the first value is the mean of duration and the second is the std value of duration.
In any case you need to write code to obtain all the SAC and duration samples in day base, and then you can compute all these parameters straightforwardly. BTW, after you obtained these samples, you could plot the histograms which show the distributions of SAC and duration.
2. Appliance code map means the appliance label (id) in the data set I used - it does not matter to the code.
Let me know if you have any further questions.

**Comment by loneharoon** [comment]
Thanks for the clarification. I have few more questions. The following screenshot is of Kettle parameters from your JSON
<img width="276" alt="screen shot 2017-12-21 at 09 52 37" src="https://user-images.githubusercontent.com/8012729/34250568-28e0f6e6-e635-11e7-81d1-050a9ca68aab.png">

1. sac:  As you mentioned this represents total energy consumption of the appliance. Is it the total energy consumption of a single day or the total (summation) energy consumption over several days.
2. sac sample: Each reading under this parameter represents total energy consumption of a different day. For example, in the kettle, you have computed sac over different 1862 days and that resulted in a list of 1862 size. Am I right?
3. Induced density of sac:  As you mentioned that first value of this parameter represents mean and the second one represents standard deviation over sac samples. I re-computed these values on your sac samples of the kettle and I found values as below. These values are different as you have reported (in the above screenshot). Have I missed something?
```
In [16]: np.mean(dic['kettle']['sac sample'])
Out[16]: 3301.2309344790547
In [17]: np.std(dic['kettle']['sac sample'])
Out[17]: 1742.0377721048508
```

4. Induced density of duration: Here we first compute total appliance usage time day wise over several days. Next, we take mean and standard deviation over these values. Am I right?

I know that you have to recall these details but these are important. And I don't want to run LBM under false settings/calculations. I want to verify each and every detail.

**Comment by MingjunZhong** [comment]
1. sac is the total energy consumption of a single day.
2. Yes, it was the sac values of different 1862 days.
3. Yes you are right they are different, but I cannot remember what made them different - they are similar though. It might be that the mean and std were computed using more than 1862 samples which are listed here. I remember the day samples were very dirty, so I removed some samples which resulted in 1862 samples.
4. Induced density of duration: yes you are right.
Hope this will help.

**Comment by loneharoon** [comment]
Thanks a lot for explanations. I appreciate your prompt responses. I hope this discussion thread will be helpful to others as well!
