### ISSUE TITLE
Am I setting LBM parameters correctly?

### ISSUE THREAD

**Issue by loneharoon** [MingjunZhong/LatentBayesianMelding#6]
I think I am not setting some parameters correctly as disaggregation accuracy is not better as compared to FHMM. Please correct me if I am doing wrong. My approach is:

1.  First, obtain population models for all appliances of a home. In my case, I have 5 appliances, the sampling rate is 1 minute and data duration is one month of a single home.
2. Next, I used these population models for disaggregation for the same home for a duration of 5 days. I updated sample_seconds to 60 by `lbm.sample_seconds = 60` after initializing  `LatentBayesianMelding()` .

Also, please clear my following doubts

1.  Currently, I called `lbm.disaggregate_chunk(mains)` once where my `mains` represents mains or aggregate signal of all 5 days. Am I supposed to divide mains into 5 chunks beforehand such that each chunk will contain data of a day? and then call mentioned function 5 times separately with a different day chunk?
2. While going through your code I don't understand line number 171 in file `latent_Bayesian_melding.py`. The line is `chunk = chunk*(((self.sample_seconds/60.0)/60.0)*10.0)`
What is this line doing? and what all these numbers are? I think I need to change them according to my sampling rate.

**Comment by MingjunZhong** [comment]
You approaches look correct. To change the sample rate, I find it in the line 38 in `demo_latentBayesianMelding.py', and line 91 in `latent_Bayesian_melding.py'. 
1. Yes it seems right - the chunk should be one day's mains, and so you will call the function 5 times. I suggest you just test your code on one day's mains, and then work on 5 days.
2. My code is tested on UK-DALE data, the data unit was Watt. The model parameters were learnt from HES data and the unit was deci-watt-hour (0.1*watt-hour). The chunk was resampled to 2minutes = 120Seconds. Here the unit of the chunk is Watt. So I wanted to convert Watt to deci-watt-hour: chunk*(120/3600)*10, which is that line. 
Thanks for pointing these problems, I should improve my code.

**Comment by loneharoon** [comment]
Thanks for the clarification.

1. Chunking on day level improved accuracy indeed
2. On further going through the code, I found that `chunk = chunk*(((self.sample_seconds/60.0)/60.0)*10.0` is nowhere used actually because method `disaggregate()` is never called in any part of the program.

**Comment by MingjunZhong** [comment]
Yes you are right, this demo code only calls disaggregate_chuck(), which is only for one day's data. If you want to apply to multiple days, then you need to call disaggregate().
